// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8VcZ48X6lVx9ga1h4dakOVgAol3BLy3A',
    appId: '1:488948795277:web:a6cb3e13d0f0ee40f49fc4',
    messagingSenderId: '488948795277',
    projectId: 'libris-571c6',
    authDomain: 'libris-571c6.firebaseapp.com',
    storageBucket: 'libris-571c6.firebasestorage.app',
    measurementId: 'G-VPP7TDM3PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_vyIqevSabrGmrmi5F0s1WWkgrNHKH4M',
    appId: '1:488948795277:android:52a7812a63fcb61ef49fc4',
    messagingSenderId: '488948795277',
    projectId: 'libris-571c6',
    storageBucket: 'libris-571c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADrEx4JTZHJQT3trOWmvrpReShEbrNsp4',
    appId: '1:488948795277:ios:767350197047b685f49fc4',
    messagingSenderId: '488948795277',
    projectId: 'libris-571c6',
    storageBucket: 'libris-571c6.firebasestorage.app',
    iosBundleId: 'com.example.libris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADrEx4JTZHJQT3trOWmvrpReShEbrNsp4',
    appId: '1:488948795277:ios:767350197047b685f49fc4',
    messagingSenderId: '488948795277',
    projectId: 'libris-571c6',
    storageBucket: 'libris-571c6.firebasestorage.app',
    iosBundleId: 'com.example.libris',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8VcZ48X6lVx9ga1h4dakOVgAol3BLy3A',
    appId: '1:488948795277:web:fe87605fd0bdd80df49fc4',
    messagingSenderId: '488948795277',
    projectId: 'libris-571c6',
    authDomain: 'libris-571c6.firebaseapp.com',
    storageBucket: 'libris-571c6.firebasestorage.app',
    measurementId: 'G-LR3Q5GB45Y',
  );
}
